on: push
name: Deploy website on push
jobs:
 web-deploy:
 name: Deploy
 runs-on: ubuntu-latest
 steps:
 - name: Get latest code
 uses: actions/checkout@v2

 - name: Sync files
 uses: SamKirkland/FTP-Deploy-Action@4.3.0
 with:
 server: ftp://153.92.220.162
 server-dir: /home/u220968159/domains/mediatekformation.xyz/public_html/public_html/
 username: u220968159.mediatekformation.xyz
 password: ${{ secrets.ftp_password }}
